name: Cultivation
version: '${version}'
main: vn.aoi.cultivation.CultivationPlugin
description: "Tu Tiên - Cultivation Plugin cho Minecraft Việt Nam"
api-version: '1.21'
load: POSTWORLD
authors:
  - AoiDev

bootstrapper: vn.aoi.cultivation.bootstrap.CultivationBootstrap

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false

commands:
  tu:
    description: "Lệnh tu luyện chính"
    aliases: [cultivation, tutien, tt, tulo]
    permission: cultivation.use

  sect:
    description: "Quản lý Tông Môn"
    aliases: [tongmon, tm, tong]
    permission: cultivation.sect.use

permissions:
  cultivation.use:
    default: true

  cultivation.admin:
    default: op
    children:
      cultivation.use: true

  cultivation.sect.use:
    default: true

  cultivation.bypass.tribulation:
    default: false
