name: AoiChan
main: vn.aoi.onii.Main
version: 1.0
api-version: 1.21

commands:
  aoi:
    description: Main command
    usage: /aoi
    permission: aoi.use

permissions:
  aoi.use:
    default: true
  aoi.admin:
    default: op
